// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sawuhvmamfznbmyjjdfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNhd3Vodm1hbWZ6bmJteWpqZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE0NzUxOTIsImV4cCI6MjA1NzA1MTE5Mn0.t1RSPI2tajRPANW6GEyJBQ2YonU_Aq-ctngzswZsStg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);